In [186]:
import glob
import cv2 as cv
import numpy as np
import matplotlib.pyplot as plt
import skimage
from sklearn.model_selection import train_test_split
import sklearn.metrics
import os
import sys
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D
from tensorflow.keras.layers import MaxPool2D
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Dropout
from tensorflow.keras.layers import Dense
from PIL import Image

In [187]:
pathc = glob.glob('circles/*.png')
paths = glob.glob('squares/*.png')
patht = glob.glob('triangles/*.png')
circle_img = []
for img in pathc:
    n = cv.imread(img)
    circle_img.append(n)
    pathc = glob.glob('circles/*.png')
square_img = []
for img in paths:
    n = cv.imread(img)
    square_img.append(n)
    pathc = glob.glob('circles/*.png')
triangle_img = []
for img in patht:
    n = cv.imread(img)
    triangle_img.append(n)

In [188]:
print(np.shape(circle_img))
print(circle_img[0])

(100, 28, 28, 3)
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]


In [189]:
circle_train, circle_test = train_test_split(circle_img, train_size = 0.8, test_size = 0.2)
triangle_train, triangle_test = train_test_split(triangle_img, train_size = 0.8, test_size = 0.2)
square_train, square_test = train_test_split(square_img, train_size = 0.8, test_size = 0.2)

In [206]:
total_train = []
total_test = []
for i in range(len(circle_train)):
    total_train.append(circle_train[i])
    total_train.append(triangle_train[i])
    total_train.append(square_train[i])
for i in range(len(circle_test)):
    total_test.append(circle_test[i])
    total_test.append(triangle_test[i])
    total_test.append(square_test[i])
print(len(total_train))
print(len(total_test))
total_train = np.array(total_train)
np.random.shuffle(total_train)
np.random.shuffle(total_test)

240
60


240

In [207]:
namelist = []
for i in range(len(total_train)):
    im = Image.fromarray(total_train[i])
    im.save("train{}.jpeg".format(i))

In [209]:
namelist = []
for i in range(len(total_test)):
    im = Image.fromarray(total_test[i])
    im.save("test{}.jpeg".format(i))